<?php

namespace Container2XAuSK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DkvatCsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dkvatCs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dkvatCs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApiAuthController::index' => ['privates', '.service_locator.VIY6kUB', 'get_ServiceLocator_VIY6kUBService', true],
            'App\\Controller\\ApiController::create' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\ApiController::delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\ApiController::show' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\ApiController::update' => ['privates', '.service_locator.ye4pU3X', 'get_ServiceLocator_Ye4pU3XService', true],
            'App\\Controller\\ApiController::users' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\OrderController::getAllOrders' => ['privates', '.service_locator.xq1js_x', 'get_ServiceLocator_Xq1jsXService', true],
            'App\\Controller\\OrderController::getOrderById' => ['privates', '.service_locator.xq1js_x', 'get_ServiceLocator_Xq1jsXService', true],
            'App\\Controller\\PanierController::addProduct' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\PanierController::create' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PanierController::getPanierByUserId' => ['privates', '.service_locator.u_JsDOX', 'get_ServiceLocator_UJsDOXService', true],
            'App\\Controller\\PanierController::removeAllProducts' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\PanierController::removeProduct' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\PanierController::validatePanier' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\ProductController::create' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProductController::find_all' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController::find_by_id' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController::update' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ApiAuthController:index' => ['privates', '.service_locator.VIY6kUB', 'get_ServiceLocator_VIY6kUBService', true],
            'App\\Controller\\ApiController:create' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\ApiController:delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\ApiController:show' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\ApiController:update' => ['privates', '.service_locator.ye4pU3X', 'get_ServiceLocator_Ye4pU3XService', true],
            'App\\Controller\\ApiController:users' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\OrderController:getAllOrders' => ['privates', '.service_locator.xq1js_x', 'get_ServiceLocator_Xq1jsXService', true],
            'App\\Controller\\OrderController:getOrderById' => ['privates', '.service_locator.xq1js_x', 'get_ServiceLocator_Xq1jsXService', true],
            'App\\Controller\\PanierController:addProduct' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\PanierController:create' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PanierController:getPanierByUserId' => ['privates', '.service_locator.u_JsDOX', 'get_ServiceLocator_UJsDOXService', true],
            'App\\Controller\\PanierController:removeAllProducts' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\PanierController:removeProduct' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\PanierController:validatePanier' => ['privates', '.service_locator.e9C_9eg', 'get_ServiceLocator_E9C9egService', true],
            'App\\Controller\\ProductController:create' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProductController:find_all' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController:find_by_id' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController:update' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ApiAuthController::index' => '?',
            'App\\Controller\\ApiController::create' => '?',
            'App\\Controller\\ApiController::delete' => '?',
            'App\\Controller\\ApiController::show' => '?',
            'App\\Controller\\ApiController::update' => '?',
            'App\\Controller\\ApiController::users' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\OrderController::getAllOrders' => '?',
            'App\\Controller\\OrderController::getOrderById' => '?',
            'App\\Controller\\PanierController::addProduct' => '?',
            'App\\Controller\\PanierController::create' => '?',
            'App\\Controller\\PanierController::getPanierByUserId' => '?',
            'App\\Controller\\PanierController::removeAllProducts' => '?',
            'App\\Controller\\PanierController::removeProduct' => '?',
            'App\\Controller\\PanierController::validatePanier' => '?',
            'App\\Controller\\ProductController::create' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::find_all' => '?',
            'App\\Controller\\ProductController::find_by_id' => '?',
            'App\\Controller\\ProductController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ApiAuthController:index' => '?',
            'App\\Controller\\ApiController:create' => '?',
            'App\\Controller\\ApiController:delete' => '?',
            'App\\Controller\\ApiController:show' => '?',
            'App\\Controller\\ApiController:update' => '?',
            'App\\Controller\\ApiController:users' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\OrderController:getAllOrders' => '?',
            'App\\Controller\\OrderController:getOrderById' => '?',
            'App\\Controller\\PanierController:addProduct' => '?',
            'App\\Controller\\PanierController:create' => '?',
            'App\\Controller\\PanierController:getPanierByUserId' => '?',
            'App\\Controller\\PanierController:removeAllProducts' => '?',
            'App\\Controller\\PanierController:removeProduct' => '?',
            'App\\Controller\\PanierController:validatePanier' => '?',
            'App\\Controller\\ProductController:create' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:find_all' => '?',
            'App\\Controller\\ProductController:find_by_id' => '?',
            'App\\Controller\\ProductController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
