<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH9gkWUd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH9gkWUd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH9gkWUd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH9gkWUd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH9gkWUd\App_KernelDevDebugContainer([
    'container.build_hash' => 'H9gkWUd',
    'container.build_id' => '181e09db',
    'container.build_time' => 1681207762,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH9gkWUd');
