<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2XAuSK8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2XAuSK8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2XAuSK8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2XAuSK8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2XAuSK8\App_KernelDevDebugContainer([
    'container.build_hash' => '2XAuSK8',
    'container.build_id' => '60e4e2f6',
    'container.build_time' => 1681850455,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2XAuSK8');
